import type { GameDefinition } from "../../RestaurantCommon/src/game/types";
export const burger: GameDefinition = {
  id: "burger",
  title: "Burger Rush",
  subtitle: { cs: "Malý stánek. Velké sny.", en: "Small diner. Big dreams." },
  accent: "#ef693c",
  dark: "#204b50",
  background: "#8dc9c4",
  price: 10,
  speed: 4,
  stations: [
    {
      id: "source",
      kind: "source",
      x: -5.6,
      z: -6.5,
      label: { cs: "Gril", en: "Grill" },
      input: null,
      output: "raw",
      seconds: 2.5,
      batch: 1,
      unlock: 0,
    },
    {
      id: "prep",
      kind: "convert",
      x: 0,
      z: -6.5,
      label: { cs: "Sestavení", en: "Assembly" },
      input: "raw",
      output: "meal",
      seconds: 1.5,
      batch: 1,
      unlock: 0,
    },
    {
      id: "counter",
      kind: "counter",
      x: -5,
      z: 2,
      label: { cs: "Výdej", en: "Counter" },
      input: "meal",
      output: "meal",
      seconds: 0,
      batch: 1,
      unlock: 0,
    },
    {
      id: "drive",
      kind: "counter",
      x: -7,
      z: -1.5,
      label: { cs: "Drive-thru", en: "Drive-thru" },
      input: "meal",
      output: "meal",
      seconds: 0,
      batch: 1,
      unlock: 9,
    },
    {
      id: "fryer",
      kind: "source",
      x: 5.6,
      z: -6.5,
      label: { cs: "Fritéza", en: "Fryer" },
      input: null,
      output: "fries",
      seconds: 3,
      batch: 2,
      unlock: 3,
    },
    {
      id: "annex",
      kind: "convert",
      x: 0,
      z: -13,
      label: { cs: "Nová příprava", en: "Annex assembly" },
      input: "raw",
      output: "meal",
      seconds: 1.5,
      batch: 3,
      unlock: 15,
    },
    {
      id: "dispatch",
      kind: "counter",
      x: 13,
      z: -5,
      label: { cs: "Expresní výdej", en: "Express counter" },
      input: "meal",
      output: "meal",
      seconds: 0,
      batch: 1,
      unlock: 16,
    },
  ],
  unlocks: [
    {
      name: { cs: "První posezení", en: "First seating" },
      description: {
        cs: "Dva hosté si konečně mohou sednout.",
        en: "A cozy place for your first guests.",
      },
      cost: 30,
      icon: "chair",
    },
    {
      name: { cs: "Další stůl", en: "Another table" },
      description: {
        cs: "Více místa, více spokojených hostů.",
        en: "More room for happy guests.",
      },
      cost: 60,
      icon: "chair",
    },
    {
      name: { cs: "Gril a fritéza", en: "Grill & fryer" },
      description: {
        cs: "Dvojnásobná výroba placek a čerstvé hranolky.",
        en: "Double patties and fresh fries.",
      },
      cost: 150,
      icon: "fire",
    },
    {
      name: { cs: "Kancelář týmu", en: "Team office" },
      description: {
        cs: "Najmi první členy svého týmu.",
        en: "Your restaurant is ready for a team.",
      },
      cost: 250,
      icon: "team",
    },
    {
      name: { cs: "Pokladní Mia", en: "Mia, the cashier" },
      description: {
        cs: "Obslouží pokladnu a vybere tržby.",
        en: "Takes payments and collects your cash.",
      },
      cost: 300,
      icon: "team",
    },
    {
      name: { cs: "Velké posezení", en: "Full dining room" },
      description: {
        cs: "Dva nové stoly a cheeseburger v nabídce.",
        en: "Two more tables and a cheeseburger menu.",
      },
      cost: 500,
      icon: "chair",
    },
    {
      name: { cs: "Kuchař Leo", en: "Leo, the cook" },
      description: {
        cs: "Zásobuje přípravu čerstvými plackami.",
        en: "Keeps the kitchen supplied with patties.",
      },
      cost: 700,
      icon: "team",
    },
    {
      name: { cs: "Uklízeč Sam", en: "Sam, the cleaner" },
      description: {
        cs: "Postará se o stoly i odpadky.",
        en: "Keeps tables clean and ready.",
      },
      cost: 900,
      icon: "spark",
    },
    {
      name: { cs: "Drive-thru", en: "Drive-thru" },
      description: {
        cs: "Otevři okénko pro hosty v autech.",
        en: "Open a new lane for hungry drivers.",
      },
      cost: 1500,
      icon: "car",
    },
    {
      name: { cs: "Turbo kuchyně", en: "Turbo kitchen" },
      description: {
        cs: "Rychlejší příprava a prémiové menu.",
        en: "Faster assembly and a premium menu.",
      },
      cost: 2200,
      icon: "fire",
    },
    {
      name: { cs: "Číšník Alex", en: "Alex, the runner" },
      description: {
        cs: "Zásobuje oba výdeje. Podnik běží sám.",
        en: "Supplies both counters. Full automation!",
      },
      cost: 3000,
      icon: "team",
    },
    {
      name: { cs: "Hvězdný podnik", en: "Neighborhood legend" },
      description: {
        cs: "Tvá restaurace je připravena na další kapitolu.",
        en: "Your restaurant is ready for its next chapter.",
      },
      cost: 8000,
      icon: "star",
    },
    {
      name: { cs: "Východní jídelna", en: "East dining wing" },
      description: {
        cs: "Přístavba se čtyřmi stoly a o 5 míst větší tácy.",
        en: "Open a dining wing with four tables and carry 5 more items.",
      },
      cost: 3500,
      icon: "bag",
    },
    {
      name: { cs: "Zahradní terasa", en: "Garden terrace" },
      description: {
        cs: "Nová terasa se čtyřmi stoly a o 35 % rychlejší tým.",
        en: "Open a terrace with four tables and a 35% faster team.",
      },
      cost: 4500,
      icon: "team",
    },
    {
      name: { cs: "Severní kuchyně", en: "North kitchen" },
      description: {
        cs: "Rozšiř kuchyni o výrobní stanici a prémiový recept.",
        en: "Add a working kitchen annex and unlock a signature recipe.",
      },
      cost: 5500,
      icon: "star",
    },
    {
      name: { cs: "Expresní křídlo", en: "Express wing" },
      description: {
        cs: "Nové křídlo s výdejem a o 50 % rychlejší výroba.",
        en: "Open an express counter wing and produce 50% faster.",
      },
      cost: 6500,
      icon: "fire",
    },
    {
      name: { cs: "Prémiový salonek", en: "Premium lounge" },
      description: {
        cs: "Dva další stoly v salonku a o 20 % vyšší tržby.",
        en: "Add two lounge tables and earn 20% more on every order.",
      },
      cost: 8000,
      icon: "spark",
    },
    {
      name: { cs: "Vstupní zahrada", en: "Entrance garden" },
      description: {
        cs: "Otevři slavnostní zahradu a získej o 50 % více offline.",
        en: "Open the landmark garden and earn 50% more offline income.",
      },
      cost: 10000,
      icon: "star",
    },
  ],
  recipes: [
    { cs: "Classic", en: "Classic" },
    { cs: "Cheeseburger", en: "Cheeseburger" },
    { cs: "Double deluxe", en: "Double deluxe" },
    { cs: "Kouřové BBQ", en: "Smoky BBQ" },
  ],
  recipeLevels: [0, 6, 10, 15],
};
